AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'app/assets/**/*'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'test/test_helper.rb'
    - 'micro-shared/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
  UseCache: false
  TargetRubyVersion: 2.2
Style/CollectionMethods:
  article_body: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find: detect
    find_all: select
    reduce: inject
Style/DotPosition:
  article_body: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing
Style/FileName:
  article_body: Use snake_case for source file names.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#snake-case-files
  Enabled: false
  Exclude: []
Style/GuardClause:
  article_body: Check for conditionals that can be replaced with guard clauses
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals
  Enabled: false
  MinBodyLength: 1
Style/IfUnlessModifier:
  article_body: Favor modifier if/unless usage when you have a single-line body.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier
  Enabled: false
  Metrics/LineLength: Max
Style/OptionHash:
  article_body: Don't use option hashes when you can use keyword arguments.
  Enabled: false
Style/PercentLiteralDelimiters:
  article_body: Use `%`-literal delimiters consistently
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-literal-braces
  Enabled: false
  PreferredDelimiters:
    '%': '()'
    '%i': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'
Style/PredicateName:
  article_body: Check the names of predicate methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#bool-methods-qmark
  Enabled: true
  NamePrefix:
    - is_
    - has_
    - have_
  NamePrefixBlacklist:
    - is_
  Exclude:
    - spec/**/*
Style/RaiseArgs:
  article_body: Checks the arguments passed to raise/fail.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#exception-class-messages
  Enabled: false
  EnforcedStyle: exploded
  SupportedStyles:
    - compact
    - exploded
Style/SignalException:
  article_body: Checks for proper usage of fail and raise.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#fail-method
  Enabled: false
  EnforcedStyle: semantic
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic
Style/SingleLineBlockParams:
  article_body: Enforces the names of some block params.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#reduce-blocks
  Enabled: false
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e
Style/SingleLineMethods:
  article_body: Avoid single-line methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-single-line-methods
  Enabled: false
  AllowIfMethodIsEmpty: true
Style/StringLiterals:
  article_body: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/StringLiteralsInInterpolation:
  article_body:
    Checks if uses of quotes inside expressions in interpolated strings
    match the configured preference.
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/TrailingCommaInLiteral:
  article_body: Checks for trailing comma in parameter lists and literals.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas
  Enabled: false
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - no_comma
Metrics/AbcSize:
  article_body:
    A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: false
  Max: 15
Metrics/ClassLength:
  article_body: Avoid classes longer than 100 lines of code.
  Enabled: false
  CountComments: false
  Max: 100
Metrics/ModuleLength:
  CountComments: false
  Max: 100
  article_body: Avoid modules longer than 100 lines of code.
  Enabled: false
Metrics/CyclomaticComplexity:
  article_body:
    A complexity metric that is strongly correlated to the number of test
    cases needed to validate a method.
  Enabled: false
  Max: 6
Metrics/MethodLength:
  article_body: Avoid methods longer than 10 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: false
  CountComments: false
  Max: 10
Metrics/ParameterLists:
  article_body: Avoid parameter lists longer than three or four parameters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#too-many-params
  Enabled: false
  Max: 5
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  article_body:
    A complexity metric geared towards measuring complexity for a human
    reader.
  Enabled: false
  Max: 7
Lint/AssignmentInCondition:
  article_body: Don't use assignment in conditions.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#safe-assignment-in-condition
  Enabled: false
  AllowSafeAssignment: true
Style/InlineComment:
  article_body: Avoid inline comments.
  Enabled: false
Style/AccessorMethodName:
  article_body: Check the naming of accessor methods for get_/set_.
  Enabled: false
Style/Alias:
  article_body: Use alias_method instead of alias.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#alias-method
  Enabled: false
Style/Documentation:
  article_body: Document classes and non-namespace modules.
  Enabled: false
Style/DoubleNegation:
  article_body: Checks for uses of double negation (!!).
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-bang-bang
  Enabled: false
Style/EachWithObject:
  article_body: Prefer `each_with_object` over `inject` or `reduce`.
  Enabled: false
Style/EmptyLiteral:
  article_body: Prefer literals to Array.new/Hash.new/String.new.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#literal-array-hash
  Enabled: false
Style/ModuleFunction:
  article_body: Checks for usage of `extend self` in modules.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#module-function
  Enabled: false
Style/OneLineConditional:
  article_body: Favor the ternary operator(?:) over if/then/else/end constructs.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#ternary-operator
  Enabled: false
Style/PerlBackrefs:
  article_body: Avoid Perl-style regex back references.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-perl-regexp-last-matchers
  Enabled: false
Style/Send:
  article_body:
    Prefer `Object#__send__` or `Object#public_send` to `send`, as `send`
    may overlap with existing methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#prefer-public-send
  Enabled: false
Style/SpecialGlobalVars:
  article_body: Avoid Perl-style global variables.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-cryptic-perlisms
  Enabled: false
Style/VariableInterpolation:
  article_body:
    Don't interpolate global, instance and class variables directly in
    strings.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#curlies-interpolate
  Enabled: false
Style/WhenThen:
  article_body: Use when x then ... for one-line cases.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#one-line-cases
  Enabled: false
Lint/EachWithObjectArgument:
  article_body: Check for immutable argument given to each_with_object.
  Enabled: true
Lint/HandleExceptions:
  article_body: Don't suppress exception.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#dont-hide-exceptions
  Enabled: false
Lint/LiteralInCondition:
  article_body: Checks of literals used in conditions.
  Enabled: false
Lint/LiteralInInterpolation:
  article_body: Checks for literals used in interpolation.
  Enabled: false
Metrics/BlockLength:
  article_body: Increase block length "Block has too many lines"
  CountComments: false
  Max: 200
